### 查询
GET http://127.0.0.1:8080/users

### 新增
POST http://127.0.0.1:8080/users
Content-Type: application/json

{
  "name": "sb "
}

### 修改
PUT http://127.0.0.1:8080/users/2
Content-Type: application/json

{
  "name": "王五"
}

### 删除
DELETE http://127.0.0.1:8080/users/1

### 查询1号用户
GET http://127.0.0.1:8080/users/1


###查询第x页
GET http://127.0.0.1:8080/users/page